
#------------------LOGIN-----------------
POST http://127.0.0.1:5001/auth/login


{
  "email": "jhondoe@gmail.com",
  "password": "1234"
}



#------------------GET PRICING-----------------
GET http://localhost:5001/get-pricing


#------------------SIGN UP-----------------
http://localhost:5001/auth/register
Content-Type: application/json



